name: CI/CD

on:
  push:
    branches: ["shuttle-independence"]
  pull_request:
    branches: ["shuttle-independence"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Spellcheck
        uses: crate-ci/typos@v1.31.1
      - name: Clippy
        run: cargo clippy --release --verbose

  cd:
    name: CD
    runs-on: ubuntu-24.04-arm
    environment: raspberry-pi
    concurrency: raspberry-pi
    needs: ci
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build
        run: cargo build --release --verbose
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TOPGG_TOKEN: ${{ secrets.TOPGG_TOKEN }}
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          cat -n "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          scp target/release/goober_bot github@${{ secrets.SERVER_ADDRESS }}:/DEPLOYMENT_TEST/goober_bot
