name: CI/CD

on:
  push:
    branches: ["shuttle-independence"]
  pull_request:
    branches: ["shuttle-independence"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: CI
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Spellcheck
        uses: crate-ci/typos@v1.31.1
      - name: Clippy
        run: cargo clippy --verbose --release

  cd:
    name: CD
    runs-on: ubuntu-24.04-arm
    environment: raspberry-pi
    concurrency: raspberry-pi
    needs: ci
    if: ${{ github.event_name == 'push' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install musl-dev
          rustup target add aarch64-unknown-linux-musl
          cargo build --verbose --release --target aarch64-unknown-linux-musl
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TOPGG_TOKEN: ${{ secrets.TOPGG_TOKEN }}
          OPENSSL_STATIC: 1
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          scp target/aarch64-unknown-linux-musl/release/goober_bot github@${{ secrets.SERVER_ADDRESS }}:/DEPLOYMENT_TEST/goober_bot
